export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";


export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';

export const ORDER_CATEGORIES_SUCCESS = 'ORDER_CATEGORIES_SUCCESS';
export const ORDER_CATEGORIES_REQUEST = 'ORDER_CATEGORIES_REQUEST';
export const ORDER_CATEGORIES_ERROR = 'ORDER_CATEGORIES_ERROR';

export const ORDER_PRODUCTS_SUCCESS = 'ORDER_PRODUCTS_SUCCESS';
export const ORDER_PRODUCTS_REQUEST = 'ORDER_PRODUCTS_REQUEST';
export const ORDER_PRODUCTS_ERROR = 'ORDER_PRODUCTS_ERROR';

export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
